### ISSUE TITLE
Character planner does not take into account Purgatorio badges

### ISSUE THREAD

**Issue by krzysztof-sikorski** [plscks/testHYPERMAP#106]
If you go to Profile Lookup tool, load a profile of a character that has the full set of 50 Exploration Badges (including recently-added Purgatorio), and then click the "Set Planner to current character" button, you are greeted with two error messages:
- "You have 40 exploration badges left. You cant explore 50 badges!"
- "You dont have that many CPs!"

**Comment by plscks** [comment]
Thanks for the report! This should be fixed up with #107 Might you have a link to a profile that this tripped up on?

**Comment by krzysztof-sikorski** [comment]
Tested on "Batziew" and it works.
