### ISSUE TITLE
Dots still appearing on map for badges

### ISSUE THREAD

**Issue by baristlucy** [plscks/testHYPERMAP#73]
Hey!
I found that on my char Lucy that the map was reverting to putting the dots in places there are no badges, like the void or just not even on the plane.
And since I'm so new at this I forgot to screen shot it so sending you this issue probably does you no good. Sorry.

**Comment by plscks** [comment]
Thanks for the issue report! I think this might be a case of an outdated browser? Is it still on going after updating to the latest version?
