### ISSUE TITLE
Hovering Over Amaravati Tiles Breaks Info Textbox

### ISSUE THREAD

**Issue by Polytonic** [plscks/testHYPERMAP#99]
**Observed Behavior**
It seems hovering over tiles in the Amaravati zone breaks the info box in the hypermap.

**Expected Behavior**
Links should be clickable after hovering over tiles in Amaravati.

**Steps to Reproduce**
1. Visit the [Hypermap](https://plscks.github.io/testHYPERMAP/hypermap.html)
1. Select Amaravati
1. Hover over any hyperlink in the info text
1. Hover over any tile in Amaravati
1. Hover over any hyperlink in the info text

Observe how 👆🏻 causes the "tile select" cursor to appear overtop the info text. 
This prevents users from clicking links in the info text.

![image](https://user-images.githubusercontent.com/5358453/100156767-556de100-2e5e-11eb-8a06-4fd43ec93313.png)

**System Information**
 • macOS 11.0.1 Big Sur
 • Chrome 87.0.4280.67
 • Safari 14.0.1

**Comment by plscks** [comment]
Thanks for using the issue tracker to report this, I (and everyone that uses the hypermap) appreciate it. I think I've found the root cause, it should be cleared up soon (depending on your local browser cache. Thanks again!
